const std = @import("std");

// Learn more about this file here: https://ziglang.org/learn/build-system
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Shared theme module. The desktop host owns the theme registry; the shell
    // imports it under the name "theme" so a single ZIGGYZAG_THEME env var
    // drives prompt accents AND terminal palette without duplicating data.
    // See docs/THEME_PROTOCOL.md.
    const theme_module = b.createModule(.{
        .root_source_file = b.path("apps/desktop/src/theme.zig"),
        .target = target,
        .optimize = optimize,
    });

    const shell_module = b.createModule(.{
        .root_source_file = b.path("apps/shell/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    shell_module.addImport("theme", theme_module);

    const exe = b.addExecutable(.{
        .name = "ziggyzag",
        .root_module = shell_module,
    });

    // This declares intent for the executable to be installed into the
    // standard location when the user invokes the "install" step (the default
    // step when running `zig build`).
    b.installArtifact(exe);

    const desktop_module = b.createModule(.{
        .root_source_file = b.path("apps/desktop/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    const desktop_exe = b.addExecutable(.{
        .name = "ziggyzag-desktop",
        .root_module = desktop_module,
    });
    if (target.result.os.tag == .windows) {
        desktop_exe.subsystem = .windows;
        // Branded application icon (Explorer / taskbar / Alt-Tab / shortcut).
        // assets/ziggyzag.ico is generated by scripts/make-icon.py.
        desktop_module.addWin32ResourceFile(.{ .file = b.path("assets/app.rc") });
        desktop_module.linkSystemLibrary("user32", .{});
        desktop_module.linkSystemLibrary("gdi32", .{});
        desktop_module.linkSystemLibrary("kernel32", .{});
    }
    if (target.result.os.tag == .macos) {
        // Wave 3: native Cocoa window host (macos_app.zig).
        // Cocoa = AppKit + Foundation (includes NSApplication, NSWindow, NSView).
        // CoreText + CoreGraphics power the terminal cell renderer.
        // libobjc provides the ObjC runtime (objc_msgSend, class registration).
        desktop_module.linkFramework("Cocoa", .{});
        desktop_module.linkFramework("CoreText", .{});
        desktop_module.linkFramework("CoreGraphics", .{});
        desktop_module.linkSystemLibrary("objc", .{});
    }
    b.installArtifact(desktop_exe);

    const agentd_exe = b.addExecutable(.{
        .name = "ziggyzag-agentd",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/agentd/src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    if (target.result.os.tag == .windows) {
        // AgentD is a stdio JSON-lines sidecar spawned by the desktop over
        // pipes — it never needs a console. As a console-subsystem binary it
        // popped a second window when the desktop launched it; the GUI
        // subsystem suppresses that (same fix as the desktop/launcher).
        agentd_exe.subsystem = .windows;
    }
    b.installArtifact(agentd_exe);

    const launcher_module = b.createModule(.{
        .root_source_file = b.path("apps/launcher/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    const launcher_desktop_module = b.createModule(.{
        .root_source_file = b.path("apps/desktop/src/lib.zig"),
        .target = target,
        .optimize = optimize,
    });
    if (target.result.os.tag == .macos) {
        launcher_desktop_module.linkFramework("Cocoa", .{});
        launcher_desktop_module.linkFramework("CoreText", .{});
        launcher_desktop_module.linkFramework("CoreGraphics", .{});
        launcher_desktop_module.linkSystemLibrary("objc", .{});
    }
    launcher_module.addImport("desktop", launcher_desktop_module);
    const launcher_exe = b.addExecutable(.{
        .name = "ziggyzag-launcher",
        .root_module = launcher_module,
    });
    if (target.result.os.tag == .windows) {
        launcher_exe.subsystem = .windows;
        launcher_module.addWin32ResourceFile(.{ .file = b.path("assets/app.rc") });
        launcher_module.linkSystemLibrary("user32", .{});
        launcher_module.linkSystemLibrary("gdi32", .{});
        launcher_module.linkSystemLibrary("kernel32", .{});
    }
    b.installArtifact(launcher_exe);

    // This *creates* a Run step in the build graph, to be executed when another
    // step is evaluated that depends on it. The next line below will establish
    // such a dependency.
    const run_cmd = b.addRunArtifact(exe);

    // This creates a build step. It will be visible in the `zig build --help` menu,
    // and can be selected like this: `zig build run`
    // This will evaluate the `run` step rather than the default, which is "install".
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    // This allows the user to pass arguments to the application in the build
    // command itself, like this: `zig build run -- arg1 arg2 etc`
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_desktop_cmd = b.addRunArtifact(desktop_exe);
    const run_desktop_step = b.step("run-desktop", "Run the all-Zig desktop host scaffold");
    run_desktop_step.dependOn(&run_desktop_cmd.step);

    const run_agentd_cmd = b.addRunArtifact(agentd_exe);
    const run_agentd_step = b.step("run-agentd", "Run the Zig-native agent runtime");
    run_agentd_step.dependOn(&run_agentd_cmd.step);
    if (b.args) |args| {
        run_agentd_cmd.addArgs(args);
    }

    const run_launcher_cmd = b.addRunArtifact(launcher_exe);
    const run_launcher_step = b.step("run-launcher", "Run the ZiggyZag launcher");
    run_launcher_step.dependOn(&run_launcher_cmd.step);

    const shell_test_module = b.createModule(.{
        .root_source_file = b.path("apps/shell/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    shell_test_module.addImport("theme", theme_module);
    const shell_tests = b.addTest(.{
        .root_module = shell_test_module,
    });
    const run_shell_tests = b.addRunArtifact(shell_tests);
    const desktop_test_module = b.createModule(.{
        .root_source_file = b.path("apps/desktop/src/lib.zig"),
        .target = target,
        .optimize = optimize,
    });
    if (target.result.os.tag == .macos) {
        desktop_test_module.linkFramework("Cocoa", .{});
        desktop_test_module.linkFramework("CoreText", .{});
        desktop_test_module.linkFramework("CoreGraphics", .{});
        desktop_test_module.linkSystemLibrary("objc", .{});
    }
    const desktop_tests = b.addTest(.{ .root_module = desktop_test_module });
    const run_desktop_tests = b.addRunArtifact(desktop_tests);
    const agentd_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/agentd/src/lib.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const run_agentd_tests = b.addRunArtifact(agentd_tests);
    const launcher_tests = b.addTest(.{
        .root_module = launcher_test_module: {
            const module = b.createModule(.{
                .root_source_file = b.path("apps/launcher/src/main.zig"),
                .target = target,
                .optimize = optimize,
            });
            const launcher_test_desktop_module = b.createModule(.{
                .root_source_file = b.path("apps/desktop/src/lib.zig"),
                .target = target,
                .optimize = optimize,
            });
            if (target.result.os.tag == .macos) {
                launcher_test_desktop_module.linkFramework("Cocoa", .{});
                launcher_test_desktop_module.linkFramework("CoreText", .{});
                launcher_test_desktop_module.linkFramework("CoreGraphics", .{});
                launcher_test_desktop_module.linkSystemLibrary("objc", .{});
            }
            module.addImport("desktop", launcher_test_desktop_module);
            break :launcher_test_module module;
        },
    });
    const run_launcher_tests = b.addRunArtifact(launcher_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_shell_tests.step);
    test_step.dependOn(&run_desktop_tests.step);
    test_step.dependOn(&run_agentd_tests.step);
    test_step.dependOn(&run_launcher_tests.step);

    // VT conformance harness: feeds a fixed CSI/OSC/erase/scroll-region/
    // alt-screen corpus into a fresh terminal.Grid and asserts grid state,
    // printing a readable diff on any mismatch. Pure logic — no Cocoa/PTY —
    // so it runs identically on every target and is safe to gate CI on.
    const vt_conformance_exe = b.addExecutable(.{
        .name = "vt-conformance",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/desktop/src/vt_conformance.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const run_vt_conformance = b.addRunArtifact(vt_conformance_exe);
    const vt_conformance_step = b.step(
        "vt-conformance",
        "Run the VT escape-sequence conformance corpus against the terminal grid",
    );
    vt_conformance_step.dependOn(&run_vt_conformance.step);
    // Fold it into the default test gate so regressions fail `zig build test`.
    test_step.dependOn(&run_vt_conformance.step);

    // Headless smoke test for the POSIX desktop launcher (macOS and Linux).
    // Compiles the desktop binary then runs scripts/smoke-desktop-posix.sh,
    // which spawns the launcher with ZIGGYZAG_DESKTOP_NO_PTY=1 (no TTY needed)
    // and verifies a clean exit and env injection.  Safe to run in CI.
    if (target.result.os.tag == .macos or target.result.os.tag == .linux) {
        const smoke_desktop_cmd = b.addSystemCommand(&.{
            "sh", "scripts/smoke-desktop-posix.sh",
        });
        smoke_desktop_cmd.step.dependOn(&desktop_exe.step);
        const smoke_desktop_step = b.step(
            "smoke-desktop",
            "Headless POSIX smoke test: launch desktop, feed exit, verify clean shutdown",
        );
        smoke_desktop_step.dependOn(&smoke_desktop_cmd.step);
    }

    // macOS application bundle: wraps the launcher/desktop/agentd/shell
    // binaries into zig-out/ZiggyZag.app with a real CFBundleIdentifier and
    // icon, so the native window has a stable identity that screen-recording
    // and automation tools (and computer-use request_access) can target by
    // name. The script builds ReleaseSafe itself; this step just invokes it.
    if (target.result.os.tag == .macos) {
        const bundle_cmd = b.addSystemCommand(&.{
            "sh", "scripts/make-macos-bundle.sh",
        });
        bundle_cmd.step.dependOn(&desktop_exe.step);
        bundle_cmd.step.dependOn(&launcher_exe.step);
        bundle_cmd.step.dependOn(&agentd_exe.step);
        bundle_cmd.step.dependOn(&exe.step);
        const bundle_step = b.step(
            "bundle",
            "Package ZiggyZag.app (Info.plist + bundle id + icon) into zig-out/",
        );
        bundle_step.dependOn(&bundle_cmd.step);
    }
}
