const std = @import("std");

// Learn more about this file here: https://ziglang.org/learn/build-system
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Shared theme module. The desktop host owns the theme registry; the shell
    // imports it under the name "theme" so a single ZIGGYZAG_THEME env var
    // drives prompt accents AND terminal palette without duplicating data.
    // See docs/THEME_PROTOCOL.md.
    const theme_module = b.createModule(.{
        .root_source_file = b.path("apps/desktop/src/theme.zig"),
        .target = target,
        .optimize = optimize,
    });

    const shell_module = b.createModule(.{
        .root_source_file = b.path("apps/shell/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    shell_module.addImport("theme", theme_module);

    const exe = b.addExecutable(.{
        .name = "ziggyzag",
        .root_module = shell_module,
    });

    // This declares intent for the executable to be installed into the
    // standard location when the user invokes the "install" step (the default
    // step when running `zig build`).
    b.installArtifact(exe);

    const desktop_module = b.createModule(.{
        .root_source_file = b.path("apps/desktop/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    const desktop_exe = b.addExecutable(.{
        .name = "ziggyzag-desktop",
        .root_module = desktop_module,
    });
    if (target.result.os.tag == .windows) {
        desktop_exe.subsystem = .windows;
        // Branded application icon (Explorer / taskbar / Alt-Tab / shortcut).
        // assets/ziggyzag.ico is generated by scripts/make-icon.py.
        desktop_module.addWin32ResourceFile(.{ .file = b.path("assets/app.rc") });
        desktop_module.linkSystemLibrary("user32", .{});
        desktop_module.linkSystemLibrary("gdi32", .{});
        desktop_module.linkSystemLibrary("kernel32", .{});
    }
    b.installArtifact(desktop_exe);

    const agentd_exe = b.addExecutable(.{
        .name = "ziggyzag-agentd",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/agentd/src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    if (target.result.os.tag == .windows) {
        // AgentD is a stdio JSON-lines sidecar spawned by the desktop over
        // pipes — it never needs a console. As a console-subsystem binary it
        // popped a second window when the desktop launched it; the GUI
        // subsystem suppresses that (same fix as the desktop/launcher).
        agentd_exe.subsystem = .windows;
    }
    b.installArtifact(agentd_exe);

    const launcher_module = b.createModule(.{
        .root_source_file = b.path("apps/launcher/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    launcher_module.addImport("desktop", b.createModule(.{
        .root_source_file = b.path("apps/desktop/src/lib.zig"),
        .target = target,
        .optimize = optimize,
    }));
    const launcher_exe = b.addExecutable(.{
        .name = "ziggyzag-launcher",
        .root_module = launcher_module,
    });
    if (target.result.os.tag == .windows) {
        launcher_exe.subsystem = .windows;
        launcher_module.addWin32ResourceFile(.{ .file = b.path("assets/app.rc") });
        launcher_module.linkSystemLibrary("user32", .{});
        launcher_module.linkSystemLibrary("gdi32", .{});
        launcher_module.linkSystemLibrary("kernel32", .{});
    }
    b.installArtifact(launcher_exe);

    // This *creates* a Run step in the build graph, to be executed when another
    // step is evaluated that depends on it. The next line below will establish
    // such a dependency.
    const run_cmd = b.addRunArtifact(exe);

    // This creates a build step. It will be visible in the `zig build --help` menu,
    // and can be selected like this: `zig build run`
    // This will evaluate the `run` step rather than the default, which is "install".
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    // This allows the user to pass arguments to the application in the build
    // command itself, like this: `zig build run -- arg1 arg2 etc`
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_desktop_cmd = b.addRunArtifact(desktop_exe);
    const run_desktop_step = b.step("run-desktop", "Run the all-Zig desktop host scaffold");
    run_desktop_step.dependOn(&run_desktop_cmd.step);

    const run_agentd_cmd = b.addRunArtifact(agentd_exe);
    const run_agentd_step = b.step("run-agentd", "Run the Zig-native agent runtime");
    run_agentd_step.dependOn(&run_agentd_cmd.step);
    if (b.args) |args| {
        run_agentd_cmd.addArgs(args);
    }

    const run_launcher_cmd = b.addRunArtifact(launcher_exe);
    const run_launcher_step = b.step("run-launcher", "Run the ZiggyZag launcher");
    run_launcher_step.dependOn(&run_launcher_cmd.step);

    const shell_test_module = b.createModule(.{
        .root_source_file = b.path("apps/shell/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    shell_test_module.addImport("theme", theme_module);
    const shell_tests = b.addTest(.{
        .root_module = shell_test_module,
    });
    const run_shell_tests = b.addRunArtifact(shell_tests);
    const desktop_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/desktop/src/lib.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const run_desktop_tests = b.addRunArtifact(desktop_tests);
    const agentd_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/agentd/src/lib.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const run_agentd_tests = b.addRunArtifact(agentd_tests);
    const launcher_tests = b.addTest(.{
        .root_module = launcher_test_module: {
            const module = b.createModule(.{
                .root_source_file = b.path("apps/launcher/src/main.zig"),
                .target = target,
                .optimize = optimize,
            });
            module.addImport("desktop", b.createModule(.{
                .root_source_file = b.path("apps/desktop/src/lib.zig"),
                .target = target,
                .optimize = optimize,
            }));
            break :launcher_test_module module;
        },
    });
    const run_launcher_tests = b.addRunArtifact(launcher_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_shell_tests.step);
    test_step.dependOn(&run_desktop_tests.step);
    test_step.dependOn(&run_agentd_tests.step);
    test_step.dependOn(&run_launcher_tests.step);
}
